# Endpoints de Aplicações (placeholder - baseado na estrutura encontrada)
/applications:
  get:
    tags:
      - Aplicações
    summary: Listar aplicações
    description: Retorna uma lista de aplicações de protocolos
    parameters:
      - name: page
        in: query
        schema:
          type: integer
          default: 1
      - name: limit
        in: query
        schema:
          type: integer
          default: 10
    responses:
      '200':
        description: Lista de aplicações
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/PaginatedResponse'
      '401':
        description: Token inválido ou expirado
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/ErrorResponse'